### ISSUE TITLE
启动一会报错

### ISSUE THREAD

**Issue by GuardYang** [zhengjim/camille#13]
{'type': 'error', 'description': "Error: can't decode byte 0x85 in position 1", 'stack': "Error: can't decode byte 0x85 in position 1\n    at <anonymous> (/script1.js:7)", 'fileName': '/script1.js', 'lineNumber': 7, 'columnNumber': 1}

**Comment by GuardYang** [comment]
目前发现是我的app会报错，其他App没有发现

**Comment by zhengjim** [comment]
方便提供下报错的app吗？

**Comment by GuardYang** [comment]
这几行注释就不会报错
// 绕过TracerPid检测
// var ByPassTracerPid = function () {
//     var fgetsPtr = Module.findExportByName('libc.so', 'fgets');
//     var fgets = new NativeFunction(fgetsPtr, 'pointer', ['pointer', 'int', 'pointer']);
//     Interceptor.replace(fgetsPtr, new NativeCallback(function (buffer, size, fp) {
//         var retval = fgets(buffer, size, fp);
//         var bufstr = Memory.readUtf8String(buffer);
//         if (bufstr.indexOf('TracerPid:') > -1) {
//             Memory.writeUtf8String(buffer, 'TracerPid:\t0');
//             console.log('tracerpid replaced: ' + Memory.readUtf8String(buffer));
//         }
//         return retval;
//     }, 'pointer', ['pointer', 'int', 'pointer']));
// };
// setImmediate(ByPassTracerPid);
