### ISSUE TITLE
检测某个应用时候不出日志

### ISSUE THREAD

**Issue by GuardYang** [zhengjim/camille#14]
你好，这边在检测某个应用时候不出日志，能否帮看下，或者加个功能：把result打印出来
![Dingtalk_20220628105803](https://user-images.githubusercontent.com/27189624/176082812-32a5b526-1da4-4544-be21-4fdfc7a0301d.jpg)

可否请大神进群里交流一下

![IMG_8396](https://user-images.githubusercontent.com/27189624/176082832-903cc61b-97b1-4f73-adb3-590d3f0f8822.PNG)

**Comment by zhengjim** [comment]
测试了下这个包，Spawn hook有问题。 新增了attach hook。  还是比较推荐使用未加固的包来测试。

**Comment by ekko-zhao** [comment]
@You-guess-guess 群聊可以再发一下吗，大哥

**Comment by GuardYang** [comment]
> @You-guess-guess 群聊可以再发一下吗，大哥
![IMG_8762 JPG](https://user-images.githubusercontent.com/27189624/180343524-3127e199-52b1-436e-974e-d0a45fcbbd60.JPG)

**Comment by gradient30** [comment]
@You-guess-guess 大哥，能拉下进讨论群不，请教请教。。我部署在Jenkins上脚本执行了但没日志- -

**Comment by zainzeng** [comment]
> > @You-guess-guess 群聊可以再发一下吗，大哥
> > ![IMG_8762 JPG](https://user-images.githubusercontent.com/27189624/180343524-3127e199-52b1-436e-974e-d0a45fcbbd60.JPG)

可以再发下么，大佬

**Comment by AshinWang** [comment]
@You-guess-guess @4everzain 两位大哥，群聊可以再发一下吗

**Comment by Greshow** [comment]
我也遇到相似的问题，群聊可以发下吗
