### ISSUE TITLE
[*] hook error need Gadget to attach on jailed Android; its default location is: C:\Users\Android-yulai\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so

### ISSUE THREAD

**Issue by hwp2009** [zhengjim/camille#15]
错误信息：
[*] hook error
need Gadget to attach on jailed Android; its default location is: C:\Users\Android-yulai\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so

**Comment by Spicely** [comment]
去https://github.com/frida/frida/releases下载 对应版本-gadget-android-arm64.so 解压后重名为 gadget-android-arm64.so 
创建文件夹 C:\Users\Android-yulai\AppData\Local\Microsoft\Windows\INetCache\frida\ 移入

**Comment by zhengjim** [comment]
安卓需要运行frida-server
