### ISSUE TITLE
采用进程监控，启动这块日志就丢了有办法解决吗

### ISSUE THREAD

**Issue by GuardYang** [zhengjim/camille#18]
之前提过的问题，我的包没有加固的，debug的包
https://github.com/zhengjim/camille/issues/14
大神可以把我交流群二维码放着么，只是技术交流，请大神指导一下

**Comment by zhengjim** [comment]
暂时没有解决的办法。 可以的，我先加你下。

**Comment by You-guess-guess** [comment]
> 暂时没有解决的办法。 可以的，我先加你下。

我的微信GuardYang1023

**Comment by zhengjim** [comment]
#20
