### ISSUE TITLE
你好，我使用了该工具出现有意外退出

### ISSUE THREAD

**Issue by MRDHR** [zhengjim/camille#2]
![image](https://user-images.githubusercontent.com/5576916/144002329-e9855720-369a-4b5a-9b59-8e1b27d680e6.png)

环境如下
模拟器 —— genymotion 
android 7.0镜像
firda server版本15.1.12
系统win11

**Comment by MRDHR** [comment]
尝试使用了
15.1.11和15.1.10版本，均会出现该问题

**Comment by MRDHR** [comment]
![image](https://user-images.githubusercontent.com/5576916/144006660-200ac1f2-8aa2-444a-8557-64312b9a1f6a.png)
已找到错误的方法为getPhoneAddressBook()

**Comment by MRDHR** [comment]
![image](https://user-images.githubusercontent.com/5576916/144006738-65c38676-da49-479e-8e34-68fe59438cef.png)

**Comment by zhengjim** [comment]
本地暂无复现，但修改了hook方法。你可以再试试看或者注释掉该方法。
