### ISSUE TITLE
小米Miui 9 (开发内测版本,已经获取了root权限) 

### ISSUE THREAD

**Issue by q384264619** [zhengjim/camille#20]
# [参考连接教程](https://zhuanlan.zhihu.com/p/500189682)
# 使用frida版本为15.1.17,15.2.2,多个版本都试了,没有效果.
# 已经在手机的/data/local/tmp中运行frida-server服务,正常启动
![企业微信截图_5322a303-7482-4ab3-a8f7-01824e9c9265](https://user-images.githubusercontent.com/17867830/181223678-1f1a1a7b-fe57-4683-be30-aa4430635987.png)
# 在mac端运行检测程序正常,但没有日志出现,如果加上-t 参数,会出现失败情况
![企业微信截图_495b651c-9574-4e72-b6c5-13b80f21e2ab](https://user-images.githubusercontent.com/17867830/181223423-a21b1394-98b3-4557-b23f-c926ada5dcf0.png)
![企业微信截图_83e45a50-06d1-4671-9414-b520127edced](https://user-images.githubusercontent.com/17867830/181224146-2a41a36d-a351-44cc-afef-75d22a73854b.png)
## 系统版本如下:
![企业微信截图_91f623e6-daf8-44e6-b8b2-84dd6227de14](https://user-images.githubusercontent.com/17867830/181225048-702b40bc-d4ee-4310-b7ad-959ac2293d65.png)
![企业微信截图_9ca4ceed-d3f2-44d1-8563-08e4a350b222](https://user-images.githubusercontent.com/17867830/181225228-e376e2dd-3047-4a9a-a076-a2e6ce17213a.png)

# 希望能得到您帮助,感谢.

**Comment by GuardYang** [comment]
你换个其他包试试，是不是和我一样有的包检测不了

**Comment by q384264619** [comment]
问题已经解决,主要是在mainfest文件中配制的入口少了一个配制,导致无法通过adb shell am start "包名"来启动应该,需要添加"com.android.categlog.DEFAULT"这个分类

**Comment by q384264619** [comment]
> 你换个其他包试试，是不是和我一样有的包检测不了
>问题已经解决,主要是在mainfest文件中配制的入口少了一个配制,导致无法通过adb shell am start "包名"来启动应该,需要添加"com.android.categlog.DEFAULT"这个分类

**Comment by q384264619** [comment]
> 你换个其他包试试，是不是和我一样有的包检测不了

问题已经解决,主要是在mainfest文件中配制的入口少了一个配制,导致无法通过adb shell am start "包名"来启动应该,需要添加"com.android.categlog.DEFAULT"这个分类
