### ISSUE TITLE
调试已经能链接 但是 ..提示 unable to connect to remote frida-server

### ISSUE THREAD

**Issue by AtlantisDe** [zhengjim/camille#22]
### 调试已经能链接 但是 ..提示 unable to connect to remote frida-server

```c#
frida-ps -U

//已经能显示相关数据.但是使用

python camille.py com.example.test

就报错..

unable to connect to remote frida-server

能提示下么 谢谢.
```

**Comment by zhengjim** [comment]
设置端口转发
adb forward tcp:27042 tcp:27042
adb forward tcp:27043 tcp:27043

**Comment by AtlantisDe** [comment]
> 设置端口转发 adb forward tcp:27042 tcp:27042 adb forward tcp:27043 tcp:27043

[*] hook error
error receiving data: 远程主机强迫关闭了一个现有的连接。

还是没能解决.具体原因不明.

**Comment by zhengjim** [comment]
手机上没启动服务端，启动后再adb forward

**Comment by AtlantisDe** [comment]
> 

好的谢谢..
