### ISSUE TITLE
Android9和12都尝试了，无法获取日志

### ISSUE THREAD

**Issue by wyh1992922** [zhengjim/camille#24]
机器Pixel 3a。已root，frida服务已经启动。
使用命令后，无法分析。
python camille.py com.package.app -f demo01.xls
![Dingtalk_20220905182809](https://user-images.githubusercontent.com/9859895/188428787-9dab667c-e30a-4bb3-a352-f1c5517e1556.jpg)

**Comment by zhengjim** [comment]
应该是这个问题 #14 #20

**Comment by wyh1992922** [comment]
但请问下有合理的解决方案吗

**Comment by zhangchuannan** [comment]
我也遇到这个问题，有解决方案吗。但是有时候又可以。

**Comment by ysrfeng** [comment]
当前frida版本用的是多少，我试了16.0.2没问题了，用未加固的包
