### ISSUE TITLE
运行提示错误

### ISSUE THREAD

**Issue by zhuigu** [zhengjim/camille#3]
![ca](https://user-images.githubusercontent.com/31404747/148156858-4dcd5c2e-2baf-4849-8e5f-cf09c64bba49.png)
三星A9s
安装MagiskFrida模块，已关闭MagiskHide

**Comment by zhengjim** [comment]
Android 版本是多少？

**Comment by zhuigu** [comment]
> Android 10
![119ac37b8cca8d848d007e91a132f18](https://user-images.githubusercontent.com/31404747/148158379-f4303c93-c53a-4fa3-93f6-6b575a622243.png)

**Comment by zhengjim** [comment]
网上下载了个酷安的包在android10上没有复现。 但发现在android10也有其他报错。  这边能提供下apk嘛？

**Comment by zhuigu** [comment]
https://linksharing.samsungcloudcn.com/hI46GbZ9PokT    MT管理器提取的酷安安装包

**Comment by zhuigu** [comment]
其它软件还会报这个错误信息
PS D:\camille> python camille.py com.dmool.anime

-----------------------------------------------------------


 .o88b.  .d8b.  .88b  d88. d888888b db      db      d88888b
d8P  Y8 d8' `8b 88'YbdP`88   `88'   88      88      88'
8P      88ooo88 88  88  88    88    88      88      88ooooo
8b      88~~~88 88  88  88    88    88      88      88~~~~~
Y8b  d8 88   88 88  88  88   .88.   88booo. 88booo. 88.
 `Y88P' YP   YP YP  YP  YP Y888888P Y88888P Y88888P Y88888P

            https://github.com/zhengjim/camille
-------------------------------------------------------------

合规检测敏感接口开始监控...
{'type': 'error', 'description': "Error: sendTextMessageInternal(): has more than one overload, use .overload(<signature>) to choose from:\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'java.lang.String')\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'int', 'boolean', 'int')", 'stack': "Error: sendTextMessageInternal(): has more than one overload, use .overload(<signature>) to choose from:\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'java.lang.String')\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'int', 'boolean', 'int')\n    at X (frida/node_modules/frida-java-bridge/lib/class-factory.js:563)\n    at K (frida/node_modules/frida-java-bridge/lib/class-factory.js:558)\n    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:925)\n    at getSMSManager (/script1.js:454)\n    at <anonymous> (/script1.js:503)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:16)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238)\n    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:230)\n    at apply (native)\n    at ne (frida/node_modules/frida-java-bridge/lib/class-factory.js:613)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:592)", 'fileName': 'frida/node_modules/frida-java-bridge/lib/class-factory.js', 'lineNumber': 563, 'columnNumber': 1}

**Comment by zhengjim** [comment]
酷安的问题，用你那包还是没能复现。暂时加了异常处理。后续再看看。其他app的bug已修复。

**Comment by zhuigu** [comment]
> 酷安的问题，用你那包还是没能复现。暂时加了异常处理。再看看。其他app的bug已修复。

![image](https://user-images.githubusercontent.com/31404747/148329688-7c79cfab-cb65-4cff-8707-4b76252b6869.png)

**Comment by zhuigu** [comment]
![image](https://user-images.githubusercontent.com/31404747/149279190-1adcf739-e952-460b-a59c-07a19099a102.png)

**Comment by zhengjim** [comment]
看样子是获取短信的问题。 你先注释掉这个getSMSManager()方法。

**Comment by zhuigu** [comment]
> 看样子是获取短信的问题。 你先注释掉这个getSMSManager()方法。

注释后可以使用，但是部分应用显示超时设置settimeout 15秒也运行失败

**Comment by zhengjim** [comment]
那估计是加固的， 我也没法子了。最好还是拿原始包来测试。
