### ISSUE TITLE
有办法检查尝试写入sdcard数据的行为吗? 小米应用市场会检查这块,目前最新版的好像无法检测到这里

### ISSUE THREAD

**Issue by LiuXinzhi94** [zhengjim/camille#30]

**Comment by zhengjim** [comment]
hook('java.io.FileOutputStream', [
        {'methodName': '$init', 'action': action, 'messages': 'FileOutputStream写文件'}
    ]);
    hook('java.io.FileInputStream', [
        {'methodName': '$init', 'action': action, 'messages': 'FileInputStream读文件'}
    ]);

**Comment by zhengjim** [comment]
可以自行添加上面的，就是会有太多结果了。所以没加进去

**Comment by LiuXinzhi94** [comment]
function customHook() {
    var action = '用户自定义hook';

     hook('java.io.File', [
         {'methodName': 'mkdirs', 'action': action, 'messages': '尝试写入sdcard创建小米市场审核可能不通过'},
         {'methodName': 'mkdir', 'action': action, 'messages': '尝试写入sdcard创建小米市场审核可能不通过'}
         //{'methodName': 'createNewFile', 'action': action, 'messages': '尝试写入sdcard创建'}
     ]);
     
     感谢回答,目前我是这样解决的 ,和小米市场监控的方法一样

**Comment by zhengjim** [comment]
👍🏻，那我加进工具，可以吧？

**Comment by LiuXinzhi94** [comment]
可以的
&nbsp;


心丶智
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月3日(星期四) 中午11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhengjim/camille] 有办法检查尝试写入sdcard数据的行为吗? 小米应用市场会检查这块,目前最新版的好像无法检测到这里 (Issue #30)





 
👍🏻，那我加进工具，可以吧？
