### ISSUE TITLE
使用最新的代码，都获取不到堆栈了 2002-11-22

### ISSUE THREAD

**Issue by happylishang** [zhengjim/camille#33]
目前只能获取   RandomAccessFile写文件这种操作
其他的敏感API都获取不到调用，之前未更新的可以

**Comment by zhengjim** [comment]
未更新的可以用代码是哪个版本的？有运行截图嘛？frida版本是多少？

**Comment by happylishang** [comment]
![image](https://user-images.githubusercontent.com/6792557/203273576-5667cd02-30dc-46db-b5e0-3d08ecffbc4b.png)
这个可以

**Comment by zhengjim** [comment]
未能复现...

**Comment by happylishang** [comment]
![image](https://user-images.githubusercontent.com/6792557/204469925-8ad8a842-1085-4b99-bee4-54cb85179ffb.png)
13上有兼容性问题  不过这个好像不是获取不到的原因
