### ISSUE TITLE
app 闪退

### ISSUE THREAD

**Issue by ChnMig** [zhengjim/camille#36]
设备: 红米k40
版本: 安卓12/MIUI13.0.7
frida: 16.0.7
问题: 使用依附进程的方式进行 hook, 在2秒钟左右 app 会闪退, 同时没有任何报错
命令: `python camille.py 同程旅行 --isattach`

**Comment by zhengjim** [comment]
应该是包加固了。我测试了一些商用加固包也是这效果。 建议使用未加固的包

**Comment by ChnMig** [comment]
> 应该是包加固了。我测试了一些商用加固包也是这效果。 建议使用未加固的包

谢谢回复, 目前跟 app 研发的同事确认过, 没有加固, 但是有代码混淆, 可能是代码混淆的原因吗?

**Comment by zhengjim** [comment]
直接用frida能hook嘛？能的话camille用-u选择下模块，看是哪个模块导致的他闪退的。

**Comment by ChnMig** [comment]
> 直接用frida能hook嘛？能的话camille用-u选择下模块，看是哪个模块导致的他闪退的。

我直接使用 `frida -U 同程旅行 -l a.js` 也会出现闪退问题, 看来是 frida 问题, 谢谢帮助

**Comment by ChnMig** [comment]
> 直接用frida能hook嘛？能的话camille用-u选择下模块，看是哪个模块导致的他闪退的。

谢谢, 目前研究了两天, 感觉是frida跟我司的软件不兼容导致的, 通过`adb logcat -b crash >error.txt` 抓取到了app 的一些闪退日志, 目前正在和 app 研发同学沟通, 不是这个项目的问题, 这个项目很好, 提供给我们很多思路, 感谢大佬🤝
