### ISSUE TITLE
TypeError: cannot read property 'overloads' of undefined

### ISSUE THREAD

**Issue by CodeGather** [zhengjim/camille#38]
[*] 2022-11-25 10:59:46 检测到安卓版本：6.0.1
[*] 2022-12-25 10:59:46 已加载模块permission,phone,system,app,location,network,camera,bluetooth,file,media,custom
TypeError: cannot read property 'overloads' of undefined
[*] hook(getPackageInfoAsUser)方法失败,请检查该方法是否存在！！！

**Comment by zhengjim** [comment]
可以忽略告警不影响使用。最新版把告警取消了
