### ISSUE TITLE
python3 camille.py  ${包名} -f demo01.xls 无法输出日志文件

### ISSUE THREAD

**Issue by sy007** [zhengjim/camille#39]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/19952631/210292954-cd216bdc-5942-46d1-8083-9487c1c426a0.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/19952631/210293029-2ac2958d-d35e-41e1-873c-a4d3bffa6380.png">

**Comment by zhengjim** [comment]
关闭程序使用 control+c 试试

**Comment by sy007** [comment]
> 关闭程序使用 control+c 试试

control+c可以

**Comment by XuZhiFan** [comment]
control+c，是在执行python3 camille.py ${包名} -f demo01.xls 命令的窗口执行？
我试了control+c好像没有反应
