### ISSUE TITLE
Error: sendTextMessageInternal(): has more than one overload

### ISSUE THREAD

**Issue by DuRunzhe** [zhengjim/camille#5]
使用Arm版本模拟器
错误信息：
 % python3 camille.py com.xx.xx -t 3
`合规检测敏感接口开始监控...
{'type': 'error', 'description': "Error: sendTextMessageInternal(): has more than one overload, use .overload(<signature>) to choose from:\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 
'boolean', 'int', 'boolean', 'int')\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'java.lang.String', 'java.lang.String', 'long')", 'stack': "Error: sendTextMessageInternal(): has more than one overload, use .overload(<signature>) to choose from:\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'int', 'boolean', 'int')\n\t.overload('java.lang.String', 'java.lang.String', 'java.lang.String', 'android.app.PendingIntent', 'android.app.PendingIntent', 'boolean', 'java.lang.String', 'java.lang.String', 'long')\n    at X (frida/node_modules/frida-java-bridge/lib/class-factory.js:563)\n    at K (frida/node_modules/frida-java-bridge/lib/class-factory.js:558)\n    at set (frida/node_modules/frida-java-bridge/lib/class-factory.js:925)\n    at getSMSManager (/script1.js:454)\n    at <anonymous> (/script1.js:503)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:11)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238)\n    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:213)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:11)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:232)\n    at perform (frida/node_modules/frida-java-bridge/index.js:192)\n    at main (/script1.js:504)\n    at apply (native)\n    at <anonymous> (frida/runtime/core.js:45)", 'fileName': 'frida/node_modules/frida-java-bridge/lib/class-factory.js', 'lineNumber': 563, 'columnNumber': 1}`

**Comment by zhengjim** [comment]
先注释掉592行getSMSManager的这个，hook短信的应该有问题。

**Comment by zhengjim** [comment]
删除getSMSManager()

**Comment by DuRunzhe** [comment]
> 

目前是这样处理的
