### ISSUE TITLE
运行提示错误-且APP自动打开后秒退。

### ISSUE THREAD

**Issue by marginqm** [zhengjim/camille#9]
[](url)camille # python3 camille.py com.youloft.calendar
-------------------------------------------------------------

合规检测敏感接口开始监控...
Error: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/com.youloft.calendar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.youloft.calendar-1/lib/arm, /data/app/com.youloft.calendar-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
Error: query(): specified argument types do not match any of:
	.overload('android.net.Uri', '[Ljava.lang.String;', 'java.lang.String', '[Ljava.lang.String;', 'java.lang.String')
	.overload('android.net.Uri', '[Ljava.lang.String;', 'java.lang.String', '[Ljava.lang.String;', 'java.lang.String', 'android.os.CancellationSignal')
^C[*] You have stoped hook.

环境：本地PC-macbook pro 、OS版本12.2.1
安卓：魅族MX6 、android版本7.1.1、frida为最新版。
<img width="1109" alt="1312" src="https://user-images.githubusercontent.com/10354473/163078952-09768ae6-042f-476f-8b5e-a6a4a674f87d.png">

**Comment by gengsena** [comment]
我的运行后，手机就重启，没有任何日志

**Comment by conghuahuadan** [comment]
同样问题

**Comment by zhengjim** [comment]
应该是使用了加固包的原因，能使用原包还是使用原包来测试。
